name: Docker Image CI - AzureCheck

on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/python3:${{ github.sha }}
    
    - run: docker push ${{ secrets.CONTAINER_REGISTRY }}/python3:${{ github.sha }}
    
    - uses: azure/container-scan@v0
      with:
        image-name: my-image:my-tag
